#!/usr/bin/env python3
"""
Convert wv_orphan_wells.csv and wv_groundwater_wells.csv into SQL files that
use INSERT ... ON CONFLICT DO NOTHING so existing rows are silently skipped.

Outputs:
  scripts/wv_orphan_wells_upsert.sql
  scripts/wv_groundwater_wells_upsert.sql
"""

import csv
import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BATCH_SIZE = 500  # rows per INSERT statement


def sql_val(v: str) -> str:
    """Render a CSV cell as a SQL literal."""
    if v == "" or v.lower() == "null":
        return "NULL"
    # Escape single quotes
    escaped = v.replace("'", "''")
    return f"'{escaped}'"


def num_val(v: str) -> str:
    """Numeric or NULL."""
    v = v.strip()
    if not v or v.lower() == "null":
        return "NULL"
    try:
        float(v)
        return v
    except ValueError:
        return "NULL"


def date_val(v: str) -> str:
    """Date string or NULL. Basic YYYY-MM-DD check."""
    v = v.strip()
    if not v or v.lower() == "null":
        return "NULL"
    if re.match(r"^\d{4}-\d{2}-\d{2}$", v):
        return f"'{v}'"
    return "NULL"


# ── Orphan wells ──────────────────────────────────────────────────────────────

ORPHAN_COLS = [
    "api_number", "well_name", "latitude", "longitude", "state", "county",
    "operator_name", "well_type", "well_status", "spud_date", "months_inactive",
    "liability_est", "field_name", "lease_name", "district",
]

def row_to_orphan_values(r: dict) -> str:
    parts = [
        sql_val(r["api_number"]),
        sql_val(r["well_name"]),
        num_val(r["latitude"]),
        num_val(r["longitude"]),
        sql_val(r["state"]),
        sql_val(r["county"]),
        sql_val(r["operator_name"]),
        sql_val(r["well_type"]),
        sql_val(r["well_status"]),
        date_val(r["spud_date"]),
        num_val(r["months_inactive"]),
        num_val(r["liability_est"]),
        sql_val(r["field_name"]),
        sql_val(r["lease_name"]),
        sql_val(r["district"]),
    ]
    return f"  ({', '.join(parts)})"


def generate_orphan_sql(csv_path: str, out_path: str) -> None:
    rows = list(csv.DictReader(open(csv_path, encoding="utf-8")))
    print(f"Generating orphan wells SQL for {len(rows):,} rows...")

    col_list = ", ".join(ORPHAN_COLS)
    insert_prefix = (
        f"INSERT INTO orphan_wells ({col_list})\nVALUES\n"
    )
    conflict_clause = "\nON CONFLICT (api_number) DO NOTHING;\n\n"

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- WV orphan wells upsert — generated by generate_upsert_sql.py\n")
        f.write("-- Skips rows whose api_number already exists.\n\n")

        batch = []
        for i, row in enumerate(rows):
            batch.append(row_to_orphan_values(row))
            if len(batch) == BATCH_SIZE or i == len(rows) - 1:
                f.write(insert_prefix)
                f.write(",\n".join(batch))
                f.write(conflict_clause)
                batch = []

    size_kb = os.path.getsize(out_path) // 1024
    print(f"Wrote {out_path} ({size_kb:,} KB)")


# ── Groundwater wells ─────────────────────────────────────────────────────────

GW_COLS = [
    "well_id", "latitude", "longitude", "state", "county",
    "well_depth_ft", "well_capacity_gpm", "water_use", "status", "year_constructed",
]

def row_to_gw_values(r: dict) -> str:
    parts = [
        sql_val(r["well_id"]),
        num_val(r["latitude"]),
        num_val(r["longitude"]),
        sql_val(r["state"]),
        sql_val(r["county"]),
        num_val(r["well_depth_ft"]),
        num_val(r["well_capacity_gpm"]),
        sql_val(r["water_use"]),
        sql_val(r["status"]),
        num_val(r["year_constructed"]),
    ]
    return f"  ({', '.join(parts)})"


def generate_gw_sql(csv_path: str, out_path: str) -> None:
    rows = list(csv.DictReader(open(csv_path, encoding="utf-8")))
    print(f"Generating groundwater wells SQL for {len(rows):,} rows...")

    col_list = ", ".join(GW_COLS)
    insert_prefix = f"INSERT INTO groundwater_wells ({col_list})\nVALUES\n"
    conflict_clause = "\nON CONFLICT (well_id) DO NOTHING;\n\n"

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- WV groundwater wells upsert — generated by generate_upsert_sql.py\n")
        f.write("-- Skips rows whose well_id already exists.\n\n")

        batch = []
        for i, row in enumerate(rows):
            batch.append(row_to_gw_values(row))
            if len(batch) == BATCH_SIZE or i == len(rows) - 1:
                f.write(insert_prefix)
                f.write(",\n".join(batch))
                f.write(conflict_clause)
                batch = []

    size_kb = os.path.getsize(out_path) // 1024
    print(f"Wrote {out_path} ({size_kb:,} KB)")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    generate_orphan_sql(
        os.path.join(SCRIPT_DIR, "wv_orphan_wells.csv"),
        os.path.join(SCRIPT_DIR, "wv_orphan_wells_upsert.sql"),
    )
    generate_gw_sql(
        os.path.join(SCRIPT_DIR, "wv_groundwater_wells.csv"),
        os.path.join(SCRIPT_DIR, "wv_groundwater_wells_upsert.sql"),
    )
    print("\nDone. Run each .sql file in the Supabase SQL editor.")
    print("The files are split into 500-row batches so they fit within the editor's limits.")
